Repository mattermost/mattermost-marketplace, pull requests merged in 2019-11, with the labels that each got.

#19 [MM-18810] Update plugins.json to include updated plugin signatures
  plugins.json
Labels: 2: Dev Review, 3: Reviews Complete

#18 MM-18593: support extra plugin metadata
  cmd/generator/main.go
  data/statik/statik.go
  go.mod
  go.sum
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/store_test.go
  plugins.json
Labels: 3: Reviews Complete

#21 MM-20135 - Update API to return single-signature for each plugin
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/plugin_test.go
  plugins.json
Labels: 2: Dev Review

#22 Fixed wrapping a nil error
  cmd/generator/main.go
Labels: 3: Reviews Complete

#20 MM-19265 - Constrain plugin versions to supporting Mattermost versions
  cmd/generator/main.go
  data/statik/statik.go
  go.mod
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/store/plugin.go
  internal/store/plugin_test.go
  internal/store/store.go
  internal/store/store_test.go
  plugins.json
Labels: 3: Reviews Complete

#23 Update plugins.json
  data/statik/statik.go
  plugins.json
Labels: 3: Reviews Complete
