Repository mattermost/mattermost-marketplace, pull requests merged in 2019-12, with the labels that each got.

#28 Handle trailing slash when building marketplace api path
  internal/api/client.go
  internal/api/client_test.go
Labels: 3: Reviews Complete

#24 [MM-18809] Update signatures with production public key
  cmd/generator/main.go
  data/statik/statik.go
  plugins.json
Labels: 3: Reviews Complete

#27 enable golangci-lint
  .circleci/config.yml
  .editorconfig
  .golangci.yml
  Makefile
  cmd/generator/logger.go
  cmd/generator/main.go
  cmd/marketplace/server.go
  internal/api/client.go
  internal/api/client_test.go
  internal/api/context.go
  internal/api/plugins.go
  internal/api/plugins_test.go
  internal/store/plugin_test.go
  internal/store/store_test.go
Labels: Tests/Not Needed

#30 Add make run
  Makefile
Labels: 3: Reviews Complete, QA Review Done

#32 [MM-21287] Add jira v2.3.1
  data/statik/statik.go
  plugins.json
Labels: 3: Reviews Complete, QA Review Done

#29 update generator to maintain all plugin versions
  Makefile
  README.md
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/plugins_test.go
  plugins.json
Labels: 3: Reviews Complete
