Repository mattermost/mattermost-marketplace, pull requests merged in 2020-10, with the labels that each got.

#124 Add a check of the license file to checklist
  CONTRIBUTING.md
Labels: 4: Reviews Complete

#126 Add v1.0.0 of mattermost-plugin-profanity-filter to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#125 Add v3.0.0 of mattermost-plugin-jira to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#131 Add v1.0.0 of mattermost-plugin-incident-response to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 1: PM Review, 2: Dev Review

#130 Add v2.0.0 of mattermost-plugin-github to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#128 [MM-29362] Allow filtering by hosting type
  cmd/generator/add.go
  data/statik/statik.go
  internal/api/plugins.go
  internal/api/plugins_request.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/merged.go
  internal/store/proxy.go
  internal/store/static.go
  plugins.json
Labels: 4: Reviews Complete

#116 [MM-27942] Add platform-specific bundles if available
  cmd/generator/add.go
  cmd/generator/bundles.go
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/plugins.go
  internal/api/plugins_request.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/merged.go
  internal/store/proxy.go
  internal/store/static.go
  plugins.json
Labels: 4: Reviews Complete

#134 Add Enterprise label to Incident Response v1.0.0
  data/statik/statik.go
  plugins.json
Labels: 2: Dev Review

#132 Merge master into production
  .github/ISSUE_TEMPLATE/add_plugin.md
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/generator/add.go
  cmd/generator/bundles.go
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/plugins.go
  internal/api/plugins_request.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/merged.go
  internal/store/proxy.go
  internal/store/static.go
  plugins.json
Labels: 4: Reviews Complete
