Repository mattermost/mattermost-marketplace, pull requests merged in 2020-01, with the labels that each got.

#33 Update URL in README
  README.md
Labels: QA Review Done

#31 [MM-21123] Add official label to all plugins
  Makefile
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/api.go
  internal/api/client.go
  internal/api/health_check.go
  internal/api/label.go
  internal/api/labels_test.go
  internal/api/plugins.go
  internal/model/label.go
  internal/model/plugin.go
  plugins.json
Labels: 3: Reviews Complete, QA Review Done

#35 Add generator add command
  cmd/generator/add.go
  cmd/generator/main.go
  go.mod
  go.sum
Labels: 3: Reviews Complete, Tests/Not Needed

#36 [MM-21122] Update plugins.json
  data/statik/statik.go
  plugins.json
Labels: 3: Reviews Complete, QA Review Done

#38 Replace existing flag for Marketplace generator with database flag
  Makefile
  cmd/generator/add.go
  cmd/generator/main.go
  internal/model/plugin.go
  internal/model/plugin_test.go
Labels: 3: Reviews Complete, Tests/Not Needed

#40 Repect ReleaseNotesURL in manifest
  cmd/generator/add.go
  cmd/generator/main.go
  cmd/marketplace/server.go
  go.mod
  go.sum
  internal/api/handler.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/plugin_test.go
Labels: 3: Reviews Complete

#39 Add Gitlab plugin v1.1.0 to the marketplace
  data/statik/statik.go
  plugins.json
Labels: 3: Reviews Complete, QA Review Done

#42 Drop "official" label from Marketplace
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/label.go
  internal/api/labels_test.go
  internal/model/label.go
  plugins.json
Labels: 3: Reviews Complete, QA Review Done
