Repository mattermost/mattermost-marketplace, pull requests merged in 2020-06, with the labels that each got.

#70 Add v0.2.0 of mattermost-plugin-skype4business to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#69 Add v1.0.0 of mattermost-plugin-github to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#73 Add v1.2.0 of mattermost-plugin-confluence to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#60 Proxy upstream support
  .circleci/config.yml
  Makefile
  README.md
  cmd/lambda/main.go
  cmd/marketplace/server.go
  go.mod
  internal/api/plugins_test.go
  internal/store/merged.go
  internal/store/merged_test.go
  internal/store/plugin_test.go
  internal/store/proxy.go
  internal/store/proxy_test.go
  internal/store/static.go
  internal/store/static_test.go
  internal/store/store.go
  internal/store/store_test.go
Labels: 4: Reviews Complete

#68 Ensure manually added plugins stay in the database
  cmd/generator/main.go
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#71 Add mattermost plugin welcomebot v1.2.0
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#76 Send Announcements for new plugins
  .github/workflows/notify-mm-blog.sh
  .github/workflows/notify-mm-blog.yml
Labels: 4: Reviews Complete

#78 Add v1.0.0 of mattermost-plugin-mscalendar to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete, QA Review Done

#80 Add v1.1.0 of mattermost-plugin-jenkins to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#79 Limit enterprise plugins to E20 installations
  cmd/generator/add.go
  data/statik/statik.go
  internal/api/helpers.go
  internal/api/plugins.go
  internal/api/plugins_request.go
  internal/api/plugins_test.go
  internal/model/label.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/merged.go
  internal/store/proxy.go
  internal/store/static.go
  plugins.json
Labels: 4: Reviews Complete

#82 Add v2.0.0 of mattermost-plugin-jitsi to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 3: QA Review
