Repository mattermost/mattermost-marketplace, pull requests merged in 2020-11, with the labels that each got.

#133 Exclude Antivirus and Welcomebot for Cloud
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#139 Add v1.1.0 of mattermost-plugin-incident-management to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#136 Run Marketplace migration commend concurrently
  cmd/generator/add.go
  cmd/generator/bundles.go
  cmd/generator/main.go
  go.mod
  go.sum
Labels: 4: Reviews Complete

#138 Add v1.5.0-cloud of mattermost-plugin-zoom to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#140 Add mattermost plugin incident management v1.1.1
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete

#141 Add matterpoll v1.4.0
  data/statik/statik.go
  plugins.json
Labels: 2: Dev Review, 3: QA Review

#142 MM-28861 Add endpoint to marketplace to retrive all versions of specified plugin.
  internal/api/client.go
  internal/api/plugins.go
  internal/model/plugin.go
  internal/store/merged.go
  internal/store/proxy_test.go
  internal/store/static.go
  internal/store/static_test.go
Labels: 2: Dev Review

#144 Merging master into production.
  cmd/generator/add.go
  cmd/generator/bundles.go
  cmd/generator/main.go
  go.mod
  go.sum
  internal/api/client.go
  internal/api/plugins.go
  internal/model/plugin.go
  internal/store/merged.go
  internal/store/proxy_test.go
  internal/store/static.go
  internal/store/static_test.go
Labels: 3: QA Review

#137 Programmatically add labels
  cmd/generator/bundles.go
  cmd/generator/main.go
  data/statik/statik.go
  internal/api/plugins_test.go
  internal/model/label.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/static.go
  plugins.json
Labels: 4: Reviews Complete
