Repository mattermost/mattermost-marketplace, pull requests merged in 2021-04, with the labels that each got.

#180 Add v1.8.0 of mattermost-plugin-incident-collaboration to the Marketp…
  data/statik/statik.go
  plugins.json
Labels: 2: Dev Review

#181 Add v2.0.1 of mattermost-plugin-github to the Marketplace
  data/statik/statik.go
  plugins.json
Labels: 4: Reviews Complete, QA Review Done

#183 Merge master into production
  .circleci/config.yml
  CONTRIBUTING.md
  Makefile
  README.md
  cmd/generator/add.go
  cmd/generator/bundles.go
  cmd/lambda/.gitignore
  cmd/lambda/main.go
  cmd/lambda/main_test.go
  data/.gitignore
  data/generate.go
  data/statik/statik.go
  go.mod
  go.sum
  internal/api/plugins.go
  internal/api/plugins_test.go
  internal/model/label.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/static.go
  internal/store/static_test.go
  plugins.json
Labels: 4: Reviews Complete

#184 Merge production into master
  plugins.json
Labels: 4: Reviews Complete

#185 Add v0.4.0 of mattermost-plugin-apps to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#182 Add v1.2.2 of mattermost-plugin-autolink to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#186 Add v1.9.1 of mattermost-plugin-incident-collaboration to the Marketplace
  plugins.json
Labels: 4: Reviews Complete
