Repository mattermost/mattermost-marketplace, pull requests merged in 2022-03, with the labels that each got.

#252 Add v3.2.0 of mattermost-plugin-jira to the Marketplace
  plugins.json
Labels: 2: Dev Review, 3: QA Review

#257 Add v0.4.2 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#258 Add v0.4.3 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#210 Update add_plugin.md
  .github/ISSUE_TEMPLATE/add_plugin.md
Labels: 1: PM Review

#259 Add v0.15.0 of focalboard to the Marketplace
  plugins.json
Labels: 2: Dev Review, 3: QA Review

#261 Add v0.4.4 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#262 Add v1.1.1 of mattermost-plugin-bitbucket to the Marketplace
  plugins.json
Labels: 3: QA Review

#263 Add v0.4.5 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#264 Add v2.1.1 of mattermost-plugin-github to the Marketplace
  plugins.json
Labels: 4: Reviews Complete
