Repository mattermost/mattermost-marketplace, pull requests merged in 2022-06, with the labels that each got.

#285 Add v0.6.0 of mattermost-plugin-todo to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#287 Add v1.6.0 of mattermost-plugin-zoom to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#286 Add v1.6.0-cloud of mattermost-plugin-zoom to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#289 Re-add v1.6.0 of mattermost-plugin-zoom to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#292 Add v0.6.1-alpha2 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 3: QA Review

#293 Revert "Add v0.6.1-alpha2 of mattermost-plugin-calls to the Marketpla…
  plugins.json
Labels: 4: Reviews Complete

#283 [MM-44569] Use mattermost-server/v6
  cmd/generator/add.go
  cmd/generator/main.go
  cmd/marketplace/server.go
  go.mod
  go.sum
  internal/api/handler.go
  internal/api/plugins_test.go
  internal/model/plugin.go
  internal/model/plugin_test.go
  internal/store/merged_test.go
  internal/store/proxy_test.go
  internal/store/static_test.go
  plugins.json
Labels: 4: Reviews Complete

#294 Add v0.6.1 of mattermost-plugin-calls to the Marketplace
  plugins.json
Labels: 4: Reviews Complete

#300 Add Playbooks v1.28.2
  plugins.json
Labels: 4: Reviews Complete

#301 Add v7.0.1 of focalboard to the Marketplace
  plugins.json
Labels: 2: Dev Review, 3: QA Review
